import type { Metadata } from 'next'
import { Syne } from 'next/font/google'
import { Inter } from 'next/font/google'
import './globals.css'
import NavMenu from '@/components/ui/NavMenu'
import Cursor from '@/components/ui/Cursor'



const inter = Inter({ subsets: ['latin'] , weight:['600']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <Cursor/>
        {/* <NavMenu/> */}
      </body>
    </html>
  )
}
